# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTracker
	pod 'RealmSwift'
	pod 'IQKeyboardManagerSwift'
  target 'FoodTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodTrackerUITests' do
    # Pods for testing
  end

end
